# 📡 USER MANUAL: ESP32 Wireless Tally System

Operational guide and technical overview for camera operators, stage technicians, and video engineers utilizing the **LOLIN32 (ESP32)** wireless Tally hardware platform.

[![Firmware Version](https://img.shields.io/badge/Firmware-v1.1--Anti--Lag-blue.svg)](#)
[![Compatibility](https://img.shields.io/badge/Compatible%20with-Tally%20Arbiter%203.x%20--%204.x-orange.svg)](#)

---

## 1. Introduction
This wireless Tally system is built on the **LOLIN32 (ESP32)** architecture. The device natively receives real-time camera switching commands directly from the central Tally Arbiter server, streamlining visual coordination on set via two primary operational states:

* **PROGRAM:** Indicates that the assigned camera is currently live (**On Air**).
* **PREVIEW:** Indicates that the assigned camera is selected in the preview bus (**Next up** to go on air).

### 🚀 Key Features of Version v1.1:
* **Anti-Lag Architecture:** Sequentially optimized linear processing that completely eliminates communication freezes or timing lags during rapid cuts or transitions on the video switcher.
* **Locked CPU Frequency:** The microcontroller clock speed is dynamically locked at **240MHz** to handle high-frequency bursts of incoming network packets without latency bottlenecks.
* **Continuous RF Power:** Wireless modem sleep modes are overridden at the hardware level (`WIFI_PS_NONE`), ensuring absolute network connection stability even when battery voltage drops to its operational floor of 3.6V.
* **Asynchronous AJAX Web Dashboard:** A highly responsive maintenance web interface that allows on-demand telemetry monitoring and hot-swapping configuration settings without needing a single webpage refresh.

---

## 2. LED Indicator Diagnostics
Internal system behaviors and live hardware statuses are actively displayed to the operator through three discrete, high-visibility light channels:

| LED Indicator | Physical State | Operational Meaning |
| :--- | :--- | :--- |
| **🔴 RED (PROGRAM)** | Solid On | The camera is currently **LIVE / ON AIR**. |
| **🟢 GREEN (PREVIEW)** | Solid On | The camera is currently selected in **PREVIEW**. |
| **🔵 BLUE (STATUS / BAT)** | Fast Blink *(0.2s)* | The Tally is actively scanning or attempting to connect to the saved WiFi network. |
| | Ultra-Fast Blink *(0.1s)* | No known networks found. The local Configuration Access Point (AP Rescue Portal) is active. |
| | Slow Blink *(2.0s)* | ⚠️ **Critical Power Alert:** Battery capacity dropped to 10% or lower. Immediate recharging required. |
| | Off | Successfully paired with the network/server, normal runtime operation, and optimal battery status. |

---

## 3. System Power-On and Initialization
The device boots up instantly and automatically as soon as it receives power via its micro-USB port or when flipping the physical hardware switch connected to the integrated lithium battery. Upon booting up, the device executes the following core initialization sequence:

1. Safely pulls the last saved WiFi network credentials, IP settings, and unique device IDs from the internal Non-Volatile Storage (**NVS**) flash partition.
2. Clocks the processor to **240MHz** and runs a clean analog read calibration routine to benchmark the initial battery charge.
3. Activates the blue status LED indicator blink pattern *(every 0.2 seconds)* and starts searching for the production wireless network.
4. Once connected to the local network, it seamlessly stabilizes data socket threads, turns off the blue status LED, and goes into active listening mode for incoming tally triggers.

---

## 4. Initial Configuration (Rescue Portal)
If the device is powered up for the first time on a new set, has undergone a hard factory reset, or the primary production WiFi network is unreachable, the Tally will automatically broadcast its own local ad-hoc setup portal:

### Step-by-Step Setup Process:
1. Using a smartphone, tablet, or laptop computer, scan for nearby networks and connect to the unencrypted open WiFi hotspot generated by the board named: **`Config-Tally-AP`**.
2. Open any web browser of your choice *(such as Chrome, Safari, Firefox, or Edge)* and manually enter the following fallback IP address in the address bar: **`192.168.4.1`**.
3. In the graphical management interface that loads on your screen, carefully fill out the following configuration fields:
   * **SSID (Network Name):** The exact name of your studio's local 2.4GHz WiFi network. You can click the magnifying glass button (🔍) to run a live scan and select a network directly from the environment dropdown list.
   * **WiFi Password:** The security password linked to your chosen studio network.
   * **Tally Arbiter Server IP:** The local IP address of the host computer or central server instance where your Tally Arbiter software is running.
   * **Server Port:** The network communication port configured on your server *(by default, this is set to `4455`)*.
   * **Device ID:** The exact, unique text identifier string assigned to this camera unit inside your Tally Arbiter software interface *(Common examples: `CAM1`, `PTZ_STAGE`, `STEADICAM`)*.
4. Click the bottom submission button marked **"Guardar y Conectar Tally"** (*Save and Connect Tally*). The hardware will write these parameters to its permanent flash memory and reboot itself to join the active live production.

---

## 5. The Web Control Panel v1.1 (Network Maintenance)
Once the Tally device is paired and running within the studio's local network infrastructure, any technical operator or video engineer can log into its live backend diagnostics by entering the following URL address into a web browser: `http://configurar-tally1.local/` *(or by checking the dynamic local IP address assigned to the hardware unit by your network router)*.

Through this asynchronous web control panel, live commands can be sent straight to the hardware core in real time without causing interference to production tasks:

* **Intelligent Battery Module:** To safeguard overall network packet execution and insulate the system from RF antenna feedback loops, the processor does not run a continuous loop of analog reading on the battery pin. The web dashboard displays the last recorded static state. To read the live battery level instantly, simply click the **"Ver nivel de batería (Dar para actualizar)"** button. This fires off a fast background AJAX injection that fetches the live cell status without dropping video tally frames.
* **Turn Off Tally:** Sends a software-driven shutdown call to the microcontroller core, instantly plunging the hardware into a deep-sleep hibernation state (`Deep Sleep`) for safe transit in equipment cases and complete cell drain protection.
* **Reset WiFi:** Severely breaks the active network connection to the studio router and forces the equipment to spin up the local rescue portal (`Config-Tally-AP`) for rapid on-location reconfiguration.

---

## 6. Physical Hardware Interaction (BOOT Button)
The tiny onboard tactile switch labeled **BOOT** *(hardwired internally to GPIO 0)* acts as a direct mechanical override for the crew to manage the hardware core:

* **Manual Sleep Call (Entering Deep Sleep):** Press and hold down the physical **BOOT** button continuously for **5 seconds**. All active indicator LEDs will shut off instantly, and the system chip will slide into an ultra-low-consumption hibernation state. To wake up the unit and resume regular operation, tap the **BOOT** button once or disconnect and reconnect the power source.
* **Factory Reset (Format NVS Memory):** Press and hold down the physical **BOOT** button continuously for **10 seconds**. The device will execute a full wipe of its persistent NVS flash memory partition, purging all saved WiFi networks, IP addresses, and Device IDs. Upon auto-rebooting, the blue LED indicator will drop into an ultra-fast strobe flash pattern *(0.1s)*, confirming that the open rescue network `Config-Tally-AP` is up and running.

---

## 7. Wireless Over-The-Air Firmware Updates (OTA)
The firmware comes pre-packaged with an integrated wireless bootloader sustained by the `ArduinoOTA` framework library. This allows deployment of updated software builds across the local network without needing to dismount the tally housing from a camera rig or hook it up via USB to a workstation:

* During the execution of an incoming network update block, both the **PROGRAM** *(Red)* and **PREVIEW** *(Green)* LED channels will light up simultaneously in a solid, unblinking state.
* The device must not be powered down, disconnected from the energy source, or manually rebooted under any circumstance while the network file transfer process is active.
* Upon reaching a 100% transfer success metric, the internal microchip will validate the code integrity, write the new block to the app layer, and self-reboot in under 5 seconds.

---

## 8. Quick Troubleshooting Guide

### 🔍 The Blue LED is constantly blinking (0.2s) and the main Tally indicators stay off
* **Root Cause:** The device is trapped in an endless network search loop. Your studio's 2.4GHz wireless router might be powered down, or the camera operator has traveled past the signal coverage area footprint.
* **Resolution:** Double-check the status of your local network access points. If the network name or password was changed, execute a hard factory reset by holding down the BOOT button for 10 seconds to prompt a clean configuration setup.

### 🔍 The Blue LED is completely off but the Tally fails to respond to Switcher cuts
* **Root Cause:** The hardware unit has successfully logged into the local WiFi pool but cannot find or establish an handshake connection with the central Tally Arbiter software instance due to a typo in the IP or Device ID parameters.
* **Resolution:** Navigate to the device's web panel interface and check that your Server IP and port fields mirror your master workstation exactly. Additionally, look at your main Tally Arbiter GUI dashboard and confirm that the **Device ID** string assigned to that specific camera is an exact, case-sensitive match *(including spaces, symbols, and capitals)* to the string saved in the hardware core of the Tally.

### 🔍 The PROGRAM (Red) and PREVIEW (Green) LEDs keep blinking back and forth rapidly
* **Root Cause:** The hardware has received an active **Flash** broadcast string command originating from the central Tally Arbiter management desk.
* **Resolution:** This is a native diagnostic feature triggered intentionally by the video engineer or technical director to physically track down which tally box corresponds to a given camera channel on a crowded set. The indicator pattern will turn itself off automatically after a few seconds, returning to live monitoring.

---

## 9. Core Technical Specifications
* **Processor Architecture:** ESP32-D0WDQ6 (32-bit Xtensa Dual-Core locked at 240MHz).
* **Wireless Connectivity:** Wi-Fi 802.11 b/g/n (2.4 GHz) with integrated PCB trace antenna array.
* **Application Layer Protocol:** Socket.IO v3 / Low-Latency Persistent WebSockets.
* **Power Optimization:** Register-level override of RF power-saving states (`WIFI_PS_NONE`) and complete software-driven deep sleep hibernation pathing.
* **Hardware Pin Mapping (Discrete GPIOs):**
  * **LED PROGRAM (Red Channel):** GPIO 25
  * **LED PREVIEW (Green Channel):** GPIO 26
  * **LED STATUS / BATTERY (Blue Channel):** GPIO 33
  * **Voltage Analog-to-Digital Converter (ADC Input):** GPIO 35
